@startuml
'autonumber
title Client Language Preference Setting
hide footbox
skinparam backgroundColor gray

skinparam sequence {
	ArrowColor black
	ActorBorderColor gray
	LifeLineBorderColor gray
	LifeLineBackgroundColor gray
	
	ParticipantBorderColor gray
	ParticipantBackgroundColor white
	ParticipantFontName Monospaced
	ParticipantFontSize 10
	ParticipantFontColor black
	
	ActorBackgroundColor white
	ActorFontColor black
	ActorFontSize 10
	ActorFontName Monospaced
}
actor User

User -[#gray]> Browser: www.page.com
activate Container
activate RequestResponse
activate Tuckey
Browser -> Container: get /
Container -> RequestResponse: <<create>>
Container -> Tuckey
Tuckey -> ClientLanguageSetter
activate ClientLanguageSetter
ClientLanguageSetter -> RequestResponse: get locale
RequestResponse --> ClientLanguageSetter: locale
ClientLanguageSetter --> ClientLanguageSetter: isLanguageSupported
note right: [en,pl,de]
alt isLanguageSupported==true
ClientLanguageSetter --> RequestResponse: set language
else [else]
ClientLanguageSetter --> RequestResponse: set default language
end
deactivate ClientLanguageSetter
Tuckey -> RequestResponse: getLanguage
RequestResponse --> Tuckey: language
alt language==defaultLanguage
Tuckey ->] : forward /
else [else]
Tuckey -> Container: redirect /language/
Container -> Browser: redirect /language/
Browser -> Container: get /language/
end
deactivate RequestResponse
deactivate Tuckey

deactivate Container

legend right
  Redirect browser for language version.
endlegend
@enduml