@startuml
'autonumber
title Client Language Preference Setting
hide footbox
skinparam backgroundColor white

skinparam sequence {
	ArrowColor black
	ActorBorderColor gray
	LifeLineBorderColor gray
	LifeLineBackgroundColor gray
	
	ParticipantBorderColor gray
	ParticipantBackgroundColor white
	ParticipantFontName Monospaced
	ParticipantFontSize 10
	ParticipantFontColor black
	
	ActorBackgroundColor white
	ActorFontColor black
	ActorFontSize 10
	ActorFontName Monospaced
}
actor User

User -[#gray]> Browser: www.page.com
activate Container
activate RequestResponse
activate Tuckey
Browser -> Container: get /language/
Container -> RequestResponse: <<create>>
Container -> Tuckey
Tuckey -> URLLanguageSetter
activate URLLanguageSetter
URLLanguageSetter -> RequestResponse: path-to:getRequestURL()
RequestResponse --> URLLanguageSetter: path-to
URLLanguageSetter -> RequestResponse: path-from:getHeader("referer")
RequestResponse --> URLLanguageSetter: path-from
URLLanguageSetter --> URLLanguageSetter: parse path-to
URLLanguageSetter --> RequestResponse: set path-from language
URLLanguageSetter --> URLLanguageSetter: parse path-from
URLLanguageSetter --> RequestResponse: set path-to language
note right: [en,pl,de]
alt isLanguageSupported==true
URLLanguageSetter --> RequestResponse: set language
else [else]
URLLanguageSetter --> RequestResponse: set default language
end
deactivate URLLanguageSetter
Tuckey -> RequestResponse: getLanguage
RequestResponse --> Tuckey: language
alt language==defaultLanguage
Tuckey ->] : forward /
else [else]
Tuckey -> Container: redirect /language/
Container -> Browser: redirect /language/
Browser -> Container: get /language/language/
end
deactivate RequestResponse
deactivate Tuckey

deactivate Container

legend right
  Redirect browser for language version.
endlegend
@enduml